#include "scripting/ecs/EntityScriptFunctions.h"
#include "scripting/ecs/ComponentFunctions.h"
#include "scripting/ecs/ScriptFunctions.h"
#include "scripting/ecs/CameraFunctions.h"
#include "scripting/ecs/TransformFunctions.h"
#include "scripting/InputFunctions.h"