#pragma once

#include "engine/CoreTypes.h"

namespace ui
{
    enum EColor
    {
        TEXT_COLOR,                             // Text color
        TEXT_DISABLED_COLOR,                    // Text color for disabled text
        WINDOW_BACKGROUND_COLOR,
        CHILD_WINDOW_BACKGROUND_COLOR,
        POPUP_BACKGROUND_COLOR,
        BORDER_COLOR,
        BORDER_SHADOW_COLOR,
        COMPONENT_BACKGROUND_COLOR,                 // Background color for components (checkbox, radio button, plots, slider, text input)
        COMPONENT_BACKGROUND_HOVERED_COLOR,
        COMPONENT_BACKGROUND_ACTIVE_COLOR,
        TITLE_BACKGROUND_COLOR,
        TITLE_BACKGROUND_ACTION_COLOR,
        TITLE_BACKGROUND_COLLAPSED_COLOR,
        MENU_BAR_BACKGROUND_COLOR,
        SCROLL_BAR_BACKGROUND_COLOR,
        SCROLL_BAR_GRAB_COLOR,
        SCROLL_BAR_GRAB_HOVERED_COLOR,
        SCROLL_BAR_GRAB_ACTIVE_COLOR,
        CHECK_MARK_COLOR,
        SLIDER_GRAB_COLOR,
        SLIDER_GRAB_ACTIVE_COLOR,
        BUTTON_COLOR,
        BUTTON_HOVERED_COLOR,
        BUTTON_ACTIVE_COLOR,
        HEADER_COLOR,
        HEADER_HOVERED_COLOR,
        HEADER_ACTIVE_COLOR,
        SEPERATOR_COLOR,
        SEPERATOR_HOVERED_COLOR,
        SEPERATOR_ACTIVE_COLOR,
        RESIZE_GRIP_COLOR,
        RESIZE_GRIP_HOVERED_COLOR,
        RESIZE_GRIP_ACTIVE_COLOR,
        TAB_HOVERED_COLOR,
        TAB_COLOR,
        TAB_SELECTED_COLOR,
        TAB_SELECTED_OVERLINE_COLOR,
        TAB_DIMMED_COLOR,
        TAB_DIMMED_SELECTED_COLOR,
        TAB_DIMMED_SELECTED_OVERLINE_COLOR,
        DOCKING_PREVIEW_COLOR,
        DOCKING_EMPTY_BACKGROUND_COLOR,
        PLOT_LINES_COLOR,
        PLOT_LINES_HOVERED_COLOR,
        PLOT_HISTOGRAM_COLOR,
        PLOT_HISTOGRAM_HOVERED_COLOR,
        TABLE_HEADER_BACKGROUND_COLOR,
        TABLE_BORDER_STRONG_COLOR,
        TABLE_BORDER_LIGHT_COLOR,
        TABLE_ROW_BACKGROUND_COLOR,
        TABLE_ROW_BACKGROUND_ALT_COLOR,
        TEXT_LINK_COLOR,
        TEXT_SELECTED_BACKGROUND_COLOR,
        DRAG_DROP_TARGET_COLOR,
        NAV_CURSOR_COLOR,
        NAV_WINDOWING_HIGHLIGHT,
        NAV_WINDOWING_DIM_BACKGROUND_COLOR,
        MODAL_WINDOW_DIM_BACKGROUND_COLOR,
    };

    uint32 GetColor(EColor colorID, f32 alpha);
}